databases:
  - name: Budget_app_development
    databaseName: budget_app_development_r35z
    user: budget_app_development_r35z_user

services:
  - type: web
    name: Budget-app-rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Budget_app_development
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
        