default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Budget_app_development
  username: "postgres"
  password: "bernabas"

production:
  <<: *default
  database: Budget_app_production
  username: Project
  password: <%= ENV["PROJECT_DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: Budget_app_test
  host: 127.0.0.1
  username: 'postgres'
  password: 'bernabas'